site_name: Experiments Engine
site_description: A platform for running experiments and analyzing results
site_url: https://experiments-engine.idinsight.github.io
repo_url: https://github.com/IDinsight/experiments-engine
theme:
  name: material
  logo: images/ExperimentsEngine-favicon-icon.svg
  favicon: images/ExperimentsEngine-favicon-icon.svg
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: amber # Change to desired color
      accent: blue   # Change to desired color
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep purple # Change to desired color
      accent: blue   # Change to desired color
  font:
    text: "Inter"
    code: "Roboto Mono"
  features:
    - navigation.tabs
    - content.code.annotate
    - content.code.copy
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - content.footnote.tooltips

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# extra:
#   katex_options: >
#     katex.render = (function(oldRender) {
#       return function(tex, element, options) {
#         element.classList.add('katex-block');
#         return oldRender(tex, element, options);
#       };
#     })(katex.render);

nav:
  - Welcome to ExE: index.md
  - Deploying: deploying.md
  - Getting Started:
    - Overview: getting-started/index.md
    - Setup your first experiment:
        - Overview: getting-started/first-experiment/index.md
        - Create an experiment: getting-started/first-experiment/create.md
        - Integrate with your application: getting-started/first-experiment/integrate.md
        - Monitor your experiment: getting-started/first-experiment/monitor.md
    - Experiments:
        - Overview: getting-started/experiments/index.md
        - Multi-Armed Bandits:
          - Overview: getting-started/experiments/mabs/index.md
          - Setting up a MAB: getting-started/experiments/mabs/setting-up.md
          - Running a MAB experiment: getting-started/experiments/mabs/run-experiment.md
        - Contextual Bandits:
            - Overview: getting-started/experiments/cmabs/index.md
            - Setting up a CMAB: getting-started/experiments/cmabs/setting-up.md
            - Running a CMAB experiment: getting-started/experiments/cmabs/run-experiment.md
        - Bayesian A/B Testing:
            - Overview: getting-started/experiments/bayes_ab/index.md
            - Setting up a Bayesian A/B Test: getting-started/experiments/bayes_ab/setting-up.md
  - Blog: blog/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      title: On this page
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - glightbox
  - search
  - blog:
      post_excerpt: required
  - open-in-new-tab
