authors:
  Sid:
    name: Sid
    description: Data Science Director
    avatar: https://raw.githubusercontent.com/IDinsight/experiments-engine/main/docs/blog/author-avatars/sid.png
  Poornima:
    name: Poornima
    description: Data Scientist
    avatar: https://raw.githubusercontent.com/IDinsight/experiments-engine/main/docs/blog/author-avatars/poornima.png
